### ISSUE TITLE
collecting csv

### ISSUE THREAD

**Issue by nafzaouiyoussef** [davidadriel64/Save_data_crash_1xbet#1]
it collecting data but not giving me the upcoming exact numbers

**Comment by davidadriel64** [comment]
> it collecting data but not giving me the upcoming exact numbers

Hello! This script is not a predictor. What it does is gather information from the website's websockets to store a history of crashes while it's activated. To create a predictor, a minimum of 100,000 data points are needed, along with the use of an algorithm to perform calculations and find the best possible path. This is a very complex task, and I could even say impossible.
